version: "3.8"

services:
  drawfc24-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=drawfc24-db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - .:/usr/src/app
